version: '3.8'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - data-service
      - training-service
      - deployment-service
    environment:
      - DATA_SERVICE_URL=http://data-service:8081
      - TRAINING_SERVICE_URL=http://training-service:8082
      - DEPLOYMENT_SERVICE_URL=http://deployment-service:8083

  data-service:
    build: ./data-service
    ports:
      - "8081:8081"
    volumes:
      - ./data:/app/data

  training-service:
    build: ./training-service
    ports:
      - "8082:8082"
    volumes:
      - ./models:/app/models
      - ./data:/app/data

  deployment-service:
    build: ./deployment-service
    ports:
      - "8083:8083"
    volumes:
      - ./models:/app/models